title: My Data Life Portfolio
description: Analista de Datos en formaci√≥n
remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Agrega esto para evitar que el sistema busque metadatos inexistentes
repository: extractor-neural/mydatalife.github.io
