title: My Data Life Portfolio
description: Analista de Datos | Portfolio & Research
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
header_pages:
  - index.md
  - proyectos.md
  - investigaciones.md
# Agrega esto para evitar que el sistema busque metadatos inexistentes
repository: extractor-neural/mydatalife.github.io
